version: '3.3'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./src
            dockerfile: Dockerfile
        image: trucorp-web-2.0
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 6000:80
   
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
            - ./src/trucorp-db.sql:/docker-entrypoint-initdb.d/trucorp-db.sql
      
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: Trucorp
            MYSQL_USER: Izra
            MYSQL_PASSWORD: Izra
        
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8088:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db